---

- name: Update grub
  ansible.builtin.command: update-grub
  changed_when: true

- name: Check for ipv6 address
  ansible.builtin.command: ip -6 a
  changed_when: false
  register: ipv6_address

- name: Reboot
  ansible.builtin.reboot:
    reboot_timeout: 3600
  when: >
    grub_change_reboot and
    ((ipv6_address.stdout and not ipv6_enabled)
    or (not ipv6_address.stdout and ipv6_enabled))
